<?php

namespace Drupal\silverback_gutenberg\Plugin\Linkit\Matcher;

use Drupal\Core\Form\FormStateInterface;
use Drupal\linkit\Plugin\Linkit\Matcher\EntityMatcher;

/**
 * @Matcher(
 *   id = "silverback:entity:media",
 *   label = @Translation("Silverback: Media"),
 *   target_entity = "media",
 *   provider = "media"
 * )
 */
class SilverbackMediaMatcher extends EntityMatcher {

  use SilverbackMatcherTrait;

  public function __construct(array $configuration, $plugin_id, $plugin_definition) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
    $this->targetType = 'media';
  }

  public function buildConfigurationForm(
    array $form,
    FormStateInterface $form_state
  ) {
    $form = parent::buildConfigurationForm(
      $form,
      $form_state
    );

    // Silverback Gutenberg does not take this setting into account anyway.
    unset($form['substitution']);

    return $form;
  }

  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state);
    // Because we unset the substitution fieldset in ::buildConfigurationForm(),
    // we need to force it to 'canonical' because
    // Drupal\silverback_gutenberg\Controller\LinkitAutocomplete() controller
    // needs that info. If the substitution type is not set, then the
    // autocomplete controller will just leave the /media/mid urls that are
    // generated by the original linkit autocomplete service intact, which means
    // they won't be replaced, on saving, with their corresponding /media/uuid
    // counterparts.
    $this->configuration['substitution_type'] = 'canonical';
  }

}
